version: '3'

services:
  web:
    build: ./web
    depends_on:
      - mongo
    ports:
      - "5000:5000"
  mongo:
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ThisIsNotAPassword

